export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const GAMES_ROUTE = "/"
export const REWIEW_ROUTE = "/rewiew"
export const GAME_ROUTE = "/game"
export const PERSONAL_ROUTE = "/personal"